"""Purpose:
Defines the shared state used across the entire LangGraph workflow.

Every node (classifier, RAG, router, agents, memory,
approval, supervisor) reads from and writes to this state.
"""
from typing import TypedDict, List
class SupportState(TypedDict):
    """
    Shared state for the customer support workflow.
    This state is passed between every LangGraph node.
    """
    # Customer's original query
    user_query: str
    # Predicted intent
    # Possible values:
    # Sales, Technical, Billing, Account, Memory
    intent: str
    # Context retrieved from RAG
    rag_context: str
    # Final response generated by the support agent
    response: str
    # Whether human approval is required
    approval_required: bool
    # Human approval status
    approved: bool
    # Conversation history (used by SQLite memory)
    history: List[str]